### PR TITLE
Update CODE_OF_CONDUCT.md

### PR DESCRIPTION
**Pull request by BeepBot99**

### CODE REVIEW

**Review by Mesure73L — CHANGES_REQUESTED** [review]
Add line 5 back and remove the "if we edit your message..." text. If you want it, put it with the correct punishment level.

**Comment by BeepBot99** [comment]
Why add line 5 back? I don't really like it because it is like this:
## Examples of safe and unsafe behavior
### Examples of safe behavior
### Examples of unsafe behavior

That is generally considered bad practice because the information is duplicated. If you have another idea for the heading instead of "examples of save and unsafe behavior" then I will do it. I will do the other thing you said in that same commit.

**Comment by Mesure73L** [comment]
It is not like that, the 
## Examples of safe and unsafe behavior
is the start of the section while
### Examples of safe behavior
says that there are examples of safe behavior following it. If you have another way that you want to display that information without removing line 5, then do that instead. Line 5 is there to start the section.

**Comment by Mesure73L** [comment]
There is also text after line 5 to explain what the section is.

**Comment by Mesure73L** [comment]
> examples of save and unsafe behavior

Also, what is "save behavior"? Is behavior in danger?

**Comment by BeepBot99** [comment]
What if I change the heading to "behavior?"

**Comment by Mesure73L** [comment]
Change it to "Behavior Examples"

**Comment by BeepBot99** [comment]
What about "Examples of Behavior?"

**Comment by Mesure73L** [comment]
What about "Examples of Safe and Unsafe Behavior"?

**Comment by BeepBot99** [comment]
No, please don't bring out things that we have already gone over. As I told you, that has repeated information. I would be fine with that if we changed the subheadings to "Safe Behavior" and "Unsafe Behavior."

**Comment by Mesure73L** [comment]
> What about "Examples of Behavior?"

just do this ig

**Review by Mesure73L — CHANGES_REQUESTED** [review]
Put the "To help us reach our goals..." below the heading like it already was. Also, the note you added is completely redundant...

**Comment by Mesure73L** [comment]
redundant = repeated information if you didnt know

**Comment by BeepBot99** [comment]
I can remove the note. But, I'm not putting that under the heading where it originally was. It is in no way related to "examples of behavior". It says follow the rules.

**Comment by Mesure73L** [comment]
That text is supposed to explain the section.

**Comment by Mesure73L** [comment]
Also, every heading is supposed to have an empty line before and after it. Your note is breaking that style.

**Comment by Mesure73L** [comment]
If you want to keep that text there then write other text below the heading that describes it better.

**Comment by Mesure73L** [comment]
I'm not trying to argue. I'm explaining my view on it.

**Review by Mesure73L — CHANGES_REQUESTED** [review]
"Please use common sense, and do not abuse the absence of a situation not listed."
Please remove the "not," because then you're making it a double negative and telling the people to abuse situations not being listed.
Also, ~~please~~ we ask that you change "Please" to "We ask that you"
A better one would be this:
"We ask that you use common sense, and not abuse the absence of a situation listed."

**Comment by BeepBot99** [comment]
> I'm not trying to argue. I'm explaining my view on it.

You're literally arguing right now. Please just listen to me and don't argue. Don't respond to this message.

**Comment by BeepBot99** [comment]
> Please remove the "not," because then you're making it a double negative and telling the people to abuse situations not being listed.

No, I'm saying don't abuse the absence of a situation that is not there.
For example, if we forgot to put something, don't abuse the fact that it is not there.
It is intended.
I will change "please" to "we ask that you."

**Comment by Mesure73L** [comment]
Okay, let me explain.

> and do not abuse the absence of a situation not listed

I don't think you realize that I wrote the **absence**. "Do not abuse the absence of a situation listed" means do not abuse a situation not being listed. "Do not abuse the absence of a situation not listed" has a double negative. It also doesn't make as much sense.

To convey the correct message, you have to remove the "not" because it has already been written, just in a different way. Please remove the "not" as it was correct before, and I am completely sure of this.

**Comment by Mesure73L** [comment]
> No, I'm saying don't abuse the absence of a situation that is not there.

Don't abuse the absence - do not abuse something that is not there
of a situation that is not there - adds on to the previous part, saying "do not abuse the situation that is not there that is not there"

**Comment by BeepBot99** [comment]
> Do not abuse the absence of a situation listed

That is saying the absence of a situation listed, but the situation is not listed. How can a situation be absent if it is listed? A situation listed means that it **is** listed, when it is not.

> Do not abuse the absence of a situation not listed.

`absence` and the second `not` do not create a double negative. They are working together. Do not abuse the absence, do not abuse the fact that it is not there, of a situation that is not there. Absence is in the predicate, but not in the object of the preposition. It is saying don't abuse the fact that something that is not there is not there.
Take this for example:
> Don't abuse the fact that the nonexistent apples are not there.

That doesn't make much sense, but it still conveys my point. It is not saying don't abuse the fact that the apples are there, it is saying don't abuse the fact that the apples that are not there are not there. They do not cancel out. It is not a double negative.

**Comment by BeepBot99** [comment]
Sure. I'll change that tonight or tomorrow.

**Comment by BeepBot99** [comment]
@Mesure73L Is this fine? Otherwise I can revert it.

**Comment by Mesure73L** [comment]
Please revert it

**Comment by BeepBot99** [comment]
@Mesure73L REVIEW THIS PLEASE

**Pull request merged**
